// <auto-generated />
namespace Fourth.DataLoads.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seed_data_Dataload_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed_data_Dataload_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171550103_seed_data_Dataload_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
