// <auto-generated />
namespace Fourth.DataLoads.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rehire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rehire));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101413155_Rehire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
