// <auto-generated/>
// This file is auto generated by BuildNumbers.targets.
using System; 
using System.Reflection; 
[assembly:AssemblyVersion("1.0.0.0")]
[assembly:AssemblyFileVersion("1.0.65534.0")]
[assembly:AssemblyInformationalVersion("1.0.65534")]
[assembly:AssemblyCompany("Company to Replace Ltd.")]
[assembly:AssemblyProduct("Product to Replace")]
[assembly:AssemblyCopyright("Copyright © 2017 Company to Replace Ltd.")]
